### ISSUE TITLE
export without node information

### ISSUE THREAD

**Issue by opskumu** [jimmidyson/prometheus-grafana-dashboards#1]
Hi,
When I export grafana json file，the json file include node information, can I export it without node information?

Thanks.

**Comment by jimmidyson** [comment]
Sadly not. This is a drawback of Grafana. As long as you have `refresh_on_load` for your template variables that shouldn't be a problem though.

**Comment by opskumu** [comment]
Ok, I see. Thanks ; ).

**Comment by opskumu** [comment]
@jimmidyson Ok, I see. Thanks ; )
